# Grammar source - http://json.org

?start: value

?value: object
        | array
        | string
        | SIGNED_NUMBER
        | "true"
        | "false"
        | "null"

array  : "[" [value ("," value)*] "]"
object : "{" [pair ("," pair)*] "}"
pair   : string ":" value

string : ESCAPED_STRING

ESCAPED_STRING : "\"" _STRING_ESC_INNER "\""
SIGNED_NUMBER: ["+"|"-"] NUMBER
WS: /[ \t\f\r\n]/+

%ignore WS
