#!/bin/sh

. tests/tap-functions
. tests/functions

plan_tests 8

ploop init -s 1g -f raw $PLOOP_IMG
ok $? "create raw ploop image"

ploop mount -f raw -d $PLOOP_DEV -b 2048 $PLOOP_IMG
ok $? "mount raw ploop"

mkfs.ext4 -j -b 4096 $PLOOP_DEV
ok $? "create fs on raw ploop"

ploop snapshot $SPACE/DiskDescriptor.xml
ok $? "take 1st snapshot for raw ploop"

ploop snapshot $SPACE/DiskDescriptor.xml
ok $? "take 2nd snapshot for raw ploop"

ploop snapshot $SPACE/DiskDescriptor.xml
ok $? "take 3rd snapshot for raw ploop"

ploop snapshot-list $SPACE/DiskDescriptor.xml
ok $? "list snapshots for raw ploop"

ploop umount -d $PLOOP_DEV
ok $? "umount raw ploop"
rm -rf $SPACE/*
