language: python

install:
# curl -sSL https://get.docker.com/ubuntu/ | sudo sh
  - sudo apt-get install -y apt-transport-https
  - sudo bash -c "echo deb https://get.docker.com/ubuntu docker main > /etc/apt/sources.list.d/docker.list"
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 36A1D7869245C8950F966E92D8576A8BA88D21E9
  - sudo apt-get update
  - sudo apt-get install -y lxc-docker

script:
  - sudo docker build -t sergeyb/plesk .
  - sudo docker run --name plesk -i -t sergeyb/plesk

notifications:
  email:
    on_success: change
    on_failure: always
