.\"	$Id$
.\"
.\" Copyright (c) 2018 Sergey Bronnikov
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate$
.Dt DEVIATION 1
.Os
.Sh NAME
.Nm deviation
.Nd is a tool to detect anomalies in time-series data.
.Sh SYNOPSIS
.Nm
.Op Fl h
.Op Fl t Ar type
.Op Fl v
.Sh DESCRIPTION
The
.Nm
is a tool to detect anomalies which is robust, from a statistical standpoint,
in the presence of seasonality and an underlying trend. The deviation tool can
be used in wide variety of contexts. For example, detecting anomalies in system
metrics after a new software release, user engagement post an A/B test, or for
problems in software testing.
.Sh USAGE

TODO

.Sh EXAMPLES
.Bd -literal

TODO

.Ed
.Sh EXIT STATUS
.Ex -std
.Sh AUTHORS
The
.Nm
utility was written by
.An Sergey Bronnikov.
