os:
  - linux
  - osx

sudo: required
dist: trusty

language: c

compiler:
  - clang
  - gcc

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install afl tidy mandoc; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install afl-fuzz tidy-html5 mandoc; fi

script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=RELEASE
  - make
  - bin/testres -s samples/junit.xml
