.\"	$Id$
.\"
.\" Copyright (c) 2018 Sergey Bronnikov
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate: September 19 2018 $
.Dt TESTRES 1
.Os
.Sh NAME
.Nm testres
.Nd A hyperfast web frontend for software testing results written in C
.Sh SYNOPSIS
.Nm
.Op Fl h
.Op Fl s Ar file
.Op Fl s Ar directory
.Op Fl v
.Sh DESCRIPTION
The
.Nm
utility knits together software testing reports.
It helps to store and analyze software testing reports.
The
.Nm
supports two modes: as console application and as CGI application.
.Sh USAGE
.Bl -tag -width Ds
.It Pa Console application
FIXME
.It Pa CGI application
FIXME
.El
.Sh FORMATS
.Nm
supports three the most popular test report formats: TAP
(TestAnythingProtocol), SubUnit and JUnit.
.Bl -tag -width Ds
.It Pa JUnit "   "
The JUnit XML Report output comes from a build tool called Nant, as opposed to
the JUnit project itself - thus it can be a little tricky to nail down an
official spec for the format, even though it's widely adopted and used.
There have been a number of attempts to codify the schema, first off there is
an XSD for JUnit.
.It Pa Test Anything Protocol
is a simple text-based interface between testing modules a test harness.
TAP started life as part of the test harness for Perl but now has
implementations in C/C++, Python, PHP, Perl and probably others by the time you
read this.
.It Pa SubUnit
is a streaming protocol for test results.
It allows communication between unit tests and a test harness.
Originally developed for unit testing in 2005 by Robert Collins.
There are two major revisions of the protocol.
Version 1 was trivially human readable but had significant defects.
Version 1.1 added encapsulation of binary streams which mitigated some of the
issues but the core remained.
Version 2 shares many of the good characteristics of Version 1 and it still
models xUnit style test execution.
.El
.Sh FILES
.Bl -tag -width "/var/www/conf/testres.css" -compact
.It Pa /var/www/conf/testres.css
Optional
.Nm
CSS style sheet.
.El
.Sh EXIT STATUS
.Ex -std
.Sh EXAMPLES
.Bd -literal

TEST REPORT (FORMAT_JUNIT)
CREATED ON: 09/12/18 - 10:58PM
    noname (0 failures, 0 errors) 47.482000
        test_bisect_serial_fail_detected STATUS_PASS
.Ed
.Sh STANDARDS
.Rs
.%A M. G. Schwern, A. Lester, A. Armstrong
.%D 2003-2007
.%T TAP 13 - The Test Anything Protocol v13
.Re
.Pp
.Rs
.%A R. Collins
.%D August 2009
.%T SubUnit: A streaming protocol for test results
.Re
.Pp
.Rs
.%A D. Robinson, K. Coar
.%D October 2004
.%R RFC 3875
.%T The Common Gateway Interface (CGI) Version 1.1
.Re
.Sh AUTHORS
.An -nosplit
The
.Nm
utility was written by
.An Sergey Bronnikov
