.\"	$Id$
.\"
.\" Copyright (c) 2018 Sergey Bronnikov <sergeyb@bronevichok.ru>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate$
.Dt TESTRES 1
.Os
.Sh NAME
.Nm testres
.Nd A hyperfast web frontend for software testing results written in C.
.Sh SYNOPSIS
.Nm testres
.Op Fl d
.Op Fl d Ar directory
.Ar
.Sh DESCRIPTION
The
.Nm
utility knits together software testing reports.
.Sh FILES
.Bl -tag -width Ds
.It Pa report.xml
Default extenstion for reports in JUnit format.
.It Pa report.tap
Default extenstion for reports in TAP (TestAnythingProtocol) format.
.It Pa report.subunit
Default extenstion for reports in SubUnit format.
.El
.Sh EXIT STATUS
.Ex -std
.Sh STANDARDS
.Bl -dash
.It
M. G. Schwern, A. Lester, A. Armstrong, TAP 13 - The Test Anything Protocol v13, 2003-2007.
.It
R. Collins. SubUnit: A streaming protocol for test results, August, 2009.
.It
D. Robinson, K. Coar, The Common Gateway Interface (CGI) Version 1.1, RFC 3875, October 2004.
.It
Mark R. Brown, FastCGI Specification, April 1996.
.Sh AUTHORS
The
.Nm
utility was written by
.An Sergey Bronnikov.
