/*
 * Copyright © 2018 Sergey Bronnikov
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *  1. Redistributions of source code must retain the above copyright notice,
 *     this list of conditions and the following disclaimer.
 *
 *  2. Redistributions in binary form must reproduce the above copyright notice,
 *     this list of conditions and the following disclaimer in the documentation
 *     and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
 * THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR
 * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
 * OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
 * OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 * ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 */

#include <stdio.h>
#include <time.h>

#include <sys/types.h>

#include "parse_common.h"
#include "ui_common.h"
#include "ui_http.h"

extern char **environ;

void print_html_headers(char *version, const char *stylesheet) {
    printf("Content-Type: text/html;charset=utf-8\n\n");
    printf("<!DOCTYPE html>\n");
    printf("<html lang='en'>\n");
    printf("<head>\n");
    printf("<title>testres</title>\n");
    printf("<meta name=\"generator\" content=\"testres %s\"/>\n", version);
    printf("<meta name=\"robots\" content=\"index, nofollow\"/>\n");
    printf("<link rel=\"stylesheet\" type=\"text/css\" href=\"%s\" media=\"all\"/>\n", stylesheet);
    printf("<link rel=\"shortcut icon\" href=\"/favicon.ico\"/>\n");
    printf("</head>\n");
    printf("<body>\n");
#ifdef DEBUG
    print_html_env();
#endif /* DEBUG */
}

void print_html_footer(char *version) {
    printf("<div><footer class=\"footer\"><small>");
	printf("generated by testres (%s)", version);
    printf("</small></footer></div>\n");
    printf("</body>\n");
    printf("</html>\n");
}

void print_html_search() {
    printf("<div align=\"center\"><form action=\"/\" method=\"get\">\n");
    printf("  <input type=\"search\" name=\"query\" value=\"\" size=\"60\" autofocus>\n");
    printf("  <button type=\"submit\" name=\"apropos\" value=\"0\">Search</button>\n");
    printf("  <br/>\n");
    printf("</form></div><br>\n");
}

void
print_html_reports(struct reportq * reports) {
    print_html_search();
    printf("<table>\n");
    printf("<tr>\n");
    printf("<th>Report ID</th>\n");
    printf("<th>Success %%</th>\n");
    printf("<th>Status</th>\n");
    printf("<th>Created On</th>\n");
    printf("</tr>\n");
    tailq_report *report_item = NULL;
    TAILQ_FOREACH(report_item, reports, entries) {
        char buffer[80] = "";
        struct tm *info = localtime(&report_item->ctime);
        strftime(buffer, 80, "%x - %I:%M%p", info);
	printf("<tr>\n");
	printf("<td><a href=\"/?show=%s\">%s</a></td>\n", report_item->id, report_item->id);
	double perc = calc_success_perc(report_item);
	if (perc >= 50) {
	   printf("<td><span class=\"label passed\">%0.0f</span></td>\n", perc);
	} else {
	   printf("<td><span class=\"label failed\">%0.0f</span></td>\n", perc);
	}
	printf("<td>\n");
	printf("<span class=\"label passed\">%d</span>\n", calc_passed(report_item));
	printf("<span class=\"label failed\">%d</span>\n", calc_failed(report_item));
	printf("<span class=\"label skipped\">%d</span>\n", calc_skipped(report_item));
	printf("</td>\n");
	printf("<td>%s</td>\n", buffer);
	printf("</tr>\n");
    }
    printf("</table>\n");
}

void
print_html_report(struct tailq_report * report) {
    print_html_search();
    printf("<b>Software Test Report (%s)</b>\n", format_string(report->format));
    char buffer[80] = "";
    struct tm *info = localtime(&report->ctime);
    strftime(buffer, 80, "%x - %I:%M%p", info);
    printf("<b>Created On: %s</b><br>\n", buffer);
    printf("<b>Report ID: %s</b><br>\n", report->id);
    if (!TAILQ_EMPTY(report->suites)) {
       print_html_suites(report->suites);
    }
}

void
print_html_suites(struct suiteq * suites) {
    tailq_suite *suite_item = NULL;
    printf("<table style=\"width:100%%\">\n");
    printf("<tr>\n");
    printf("<th>Name</th>\n");
    printf("<th>Status</th>\n");
    printf("<th>Created On</th>\n");
    printf("</tr>\n");
    TAILQ_FOREACH(suite_item, suites, entries) {
	printf("<tr>\n");
	const char *name = NULL;
	if (suite_item->name == (char *) NULL) {
		name = suite_item->name;
	} else {
		name = "noname";
	}
	printf("<td>%s</td>\n", name);
	printf("<td>%s</td>\n", "FIXME");
	printf("<td>%s</td>\n", suite_item->timestamp);
	printf("</tr>\n");
	if (!TAILQ_EMPTY(suite_item->tests)) {
		print_html_tests(suite_item->tests);
	}
    }
    printf("</table>\n");
}

void
print_html_tests(struct testq * tests) {
	tailq_test *test_item = NULL;
	TAILQ_FOREACH(test_item, tests, entries) {
		printf("<div>");
		printf("%10s ", test_item->name);
		printf("%10s ", status_string(test_item->status));
		printf("</div>\n");
		if (test_item->time != (char *) NULL) {
			printf("(%5ss) ", test_item->time);
		}
		if (test_item->comment != NULL) {
			printf("Comment: %5s", test_item->comment);
		}
		printf("\n");
	}
}

void
print_plot_aggregated(struct reportq *reports) {
    printf("<svg width=\"100%%\" height=\"100%%\">\n");
    printf("<g transform=\"translate(50,50)\"\n>");
    printf("<rect x=\"0\" y=\"0\" width=\"150\" height=\"50\" style=\"fill:red;\" />\n");
    printf("</g>\n");
    printf("</svg>\n");
}

void print_html_env() {
    int i = 1;
    char *s = *environ;
    printf("<pre>\n");
    for (; s; i++) {
        printf("%s\n", s);
        s = *(environ + i);
    }
    printf("</pre>\n");
}
