/*
 * Copyright © 2018 Sergey Bronnikov
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *  1. Redistributions of source code must retain the above copyright notice,
 *     this list of conditions and the following disclaimer.
 *
 *  2. Redistributions in binary form must reproduce the above copyright notice,
 *     this list of conditions and the following disclaimer in the documentation
 *     and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
 * THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR
 * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
 * OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
 * OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 * ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 */

#include <stdio.h>
#include <time.h>

#include <sys/types.h>

#include "parse_common.h"
#include "ui_common.h"
#include "ui_http.h"

void 
print_html_headers(char *version)
{
	printf("Content-Type: text/html;charset=utf-8\n\n");
	printf("<!DOCTYPE html>\n");
	printf("<html lang='en'>\n");
	printf("<head>\n");
	printf("<title></title>\n");
	printf("<meta name='generator' content='testres %s'/>\n", version);
	printf("<meta name='robots' content='index, nofollow'/>\n");
	printf("<link rel='stylesheet' type='text/css' href='/testres.css'/>\n");
	printf("<link rel='shortcut icon' href='/favicon.ico'/>\n");
	printf("</head>\n");
	printf("<body>\n");
}

void 
print_html_footer(char *version)
{
	printf("<div class='footer'>generated by <a href='https://github.con/ligurio/testres'>testres %s</a></div>", version);
	printf("</body>");
	printf("</html>");
}

void 
print_html_reports_index(struct reportq * reports)
{
	tailq_report *report_item = NULL;
	TAILQ_FOREACH(report_item, reports, entries) {
		printf("<b>report %s</b><br>\n", format_string(report_item->format));
	}
}

void 
print_html_reports(struct reportq * reports)
{
	tailq_report *report_item = NULL;
	TAILQ_FOREACH(report_item, reports, entries) {
		print_html_report(report_item);
	}
}

void 
print_html_report(struct tailq_report * report)
{
	printf("<b>TEST REPORT (%s)</b>\n", format_string(report->format));
	char buffer[80] = "";
	struct tm *info = localtime(&report->ctime);
	strftime(buffer, 80, "%x - %I:%M%p", info);
	printf("<b>CREATED ON: %s</b><br>\n", buffer);
	if (!TAILQ_EMPTY(report->suites)) {
		print_html_suites(report->suites);
	}
}

void 
print_html_suites(struct suiteq * suites)
{
	tailq_suite *suite_item = NULL;
	TAILQ_FOREACH(suite_item, suites, entries) {
                const char *name = NULL;
		if (suite_item->name == (char *) NULL) {
			name = suite_item->name;
		} else {
			name = "noname";
		}
		printf("<div>%10s</div>", name);
		printf("(%d failures, %d errors) ", suite_item->n_failures, suite_item->n_errors);
		printf("%5f ", suite_item->time);
		if (suite_item->timestamp != (char *) NULL) {
			printf("%10s ", suite_item->timestamp);
		}
		if (suite_item->hostname != (char *) NULL) {
			printf("%10s ", suite_item->hostname);
		}
		printf("\n");
		if (!TAILQ_EMPTY(suite_item->tests)) {
			print_html_tests(suite_item->tests);
		}
	}
}

void 
print_html_tests(struct testq * tests)
{
	tailq_test *test_item = NULL;
	TAILQ_FOREACH(test_item, tests, entries) {
		printf("<div>");
		printf("%10s ", test_item->name);
		printf("%10s ", status_string(test_item->status));
		printf("</div>\n");
		if (test_item->time != (char *) NULL) {
			printf("(%5ss) ", test_item->time);
		}
		if (test_item->comment != NULL) {
			printf("Comment: %5s", test_item->comment);
		}
		printf("\n");
	}
}
