name: Run tests

on:
  push:
  pull_request:

jobs:
  run-tests:
    if: |
      github.event_name == 'push' ||
      github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name != github.repository
    strategy:
      matrix:
        tarantool-version: ["2.8"]
        include:
          - tarantool-version: "2.7"
            coveralls: true
      fail-fast: false
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@master

      - name: Setup Tarantool
        uses: tarantool/setup-tarantool@v1
        with:
          tarantool-version: ${{ matrix.tarantool-version }}

      - name: Install requirements
        run: make dependences

      - name: Run tests and code coverage analysis
        run: make coverage

      - name: Send code coverage to coveralls.io
        run: make coveralls
        if: ${{ matrix.coveralls }}
